server:
  port: 8080
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br
file:
  upload-dir: C:/Users/va001/Documents/projetos/Code/uploadDir
logging:
  level:
    net.sf.jasperreports: TRACE
email:
  subject: "Default Subject"
  message: "Default Message"
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: ${JWT_EXPIRE_MS:3600000}
spring:
  application:
    name: rest-with-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_springboot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true

